version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: test
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./.mysql/:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-hlocalhost", "-ptest"]
      interval: 5s
      timeout: 1s
      retries: 20
      start_period: 5s

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - 4566:4566
    environment:
      - SERVICES=s3
    volumes:
      - ./.localstack:/etc/localstack/init/ready.d
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "curl", "localhost:4566"]
      interval: 5s
      timeout: 1s
      retries: 20
      start_period: 5s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 3000:3000
    env_file:
      - .env.development
    volumes:
      - ./src:/app/src
    depends_on:
      mysql:
        condition: service_healthy
      localstack:
        condition: service_healthy
    